source 'https://github.ehealthinnovation.org/PHIT/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs'
use_frameworks!

target 'CCBluetooth_Example' do
  pod 'CCBluetooth', :path => '../'
  pod 'CCToolbox', :git => 'https://github.com/uhnmdi/CCToolbox.git'

  target 'CCBluetooth_Tests' do
    inherit! :search_paths
  end
end
